// 2026 FIFA World Cup (Canada/Mexico/USA) — all 48 qualified teams.
export const WORLD_CUP_TEAMS = [
  'Algeria',
  'Argentina',
  'Australia',
  'Austria',
  'Belgium',
  'Bosnia and Herzegovina',
  'Brazil',
  'Cabo Verde',
  'Canada',
  'Colombia',
  'Croatia',
  'Curaçao',
  'Czechia',
  'DR Congo',
  "Côte d'Ivoire",
  'Ecuador',
  'Egypt',
  'England',
  'France',
  'Germany',
  'Ghana',
  'Haiti',
  'IR Iran',
  'Iraq',
  'Japan',
  'Jordan',
  'Korea Republic',
  'Mexico',
  'Morocco',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Panama',
  'Paraguay',
  'Portugal',
  'Qatar',
  'Saudi Arabia',
  'Scotland',
  'Senegal',
  'South Africa',
  'Spain',
  'Sweden',
  'Switzerland',
  'Tunisia',
  'Türkiye',
  'United States',
  'Uruguay',
  'Uzbekistan',
].sort((a, b) => a.localeCompare(b))
